# Generated by Django 3.1 on 2023-05-07 13:48

import authentication.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'super'), (2, 'admin'), (3, 'user')], help_text='is Admin , Leader , Member or Judge')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', authentication.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.user')),
                ('f_name', models.CharField(blank=True, max_length=128, null=True)),
                ('l_name', models.CharField(blank=True, max_length=128, null=True)),
                ('national_id', models.CharField(blank=True, max_length=10, null=True)),
                ('prof_id', models.CharField(blank=True, max_length=10, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(max_length=11, unique=True)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('major', models.CharField(blank=True, max_length=128, null=True)),
                ('orientation', models.CharField(blank=True, max_length=128, null=True)),
                ('password', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
